### ISSUE TITLE
Only limiting flatMap4 is very limiting. Needs more flatMaps

### ISSUE THREAD

**Issue by kshitij8** [twitter/nodes#9]
We regularly hit the flatMap4 bottle-neck.  
Possibly adding flatMap 5 through 8 would be useful

**Comment by ysaraf** [comment]
Makes sense. Want to send out a fix?

**Comment by kshitij8** [comment]
Added pull request for the same.  
Though I can't help but feel that Node class has become very big (and probably can use some refactoring)
